version: "3.3"
services:
  api:
    image: node:lts-alpine3.14
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    links:
      - mysql-server
    depends_on:
      - mysql-server
  mysql-server:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    entrypoint: "bash -c 'echo -e \"CREATE DATABASE IF NOT EXISTS app_test;\" > /docker-entrypoint-initdb.d/create_app_test_db.sql &&
                          /entrypoint.sh mysqld'"
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    links:
      - api
    depends_on:
      - api
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./images:/sites/images
volumes:
  mysqldata:
    driver: local